# Generated by Django 5.0.1 on 2024-01-17 07:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EMS', '0008_alter_employee_domain'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistrationID',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_id', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='employee',
            name='registration_id',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='registrationID', to='EMS.registrationid'),
        ),
    ]
