# Generated by Django 5.0.1 on 2024-01-17 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EMS', '0010_alter_employee_domain'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='domain',
        ),
    ]
