# Generated by Django 5.0.1 on 2024-01-17 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EMS', '0011_remove_employee_domain'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='registration_id',
        ),
        migrations.AddField(
            model_name='domain',
            name='domain_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
