# Generated by Django 5.0.1 on 2024-01-17 10:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EMS', '0012_remove_employee_registration_id_domain_domain_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='employee_domain',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='domain', to='EMS.domain'),
        ),
    ]
