# Generated by Django 5.0.1 on 2024-01-17 10:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EMS', '0013_employee_employee_domain'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='registration_id',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='registrationID', to='EMS.registrationid'),
        ),
        migrations.AlterField(
            model_name='domain',
            name='domain_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='registrationid',
            name='registration_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
