# Generated by Django 5.0.8 on 2024-09-01 02:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EMS', '0014_employee_registration_id_alter_domain_domain_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='domain',
            options={'ordering': ['id']},
        ),
    ]
